### ISSUE TITLE
overhaul of tft-alt-fw

### ISSUE THREAD

**Issue by darkspr1te** [delwinbest/MKS-TFT28#1]
So i've overhauled /variant enough so out of the box UTFT/URTOUCH(calibrated)/SD Card, EEPROM-SPI/I2CPROM/All uarts 1/2/3 (HW) , External SD/SPI , RTC/PWM workings using most default demos, and i've dome some examples on top, i cannot get platformio to output a file with  vectors for 0x8000000 only 0x8007000  despite my io additions, DM me at igeekcrg  at  gmail.com if you want to pull req the new changes as i wont be pushing them for while.
darkspr1te

**Comment by delwinbest** [comment]
@darkspr1te  Some great stuff in your recent commits! I see LCD Register reads, is that working!!!?? Also the PWM backlight. The Buzzer is also on a PWM pin so I'll find some time to bring the two implementations in sync. It's been busy this past month. 

As for the vectors, let me add a switch for that in platformio.ini.

**Comment by darkspr1te** [comment]
Yeah thats working LCD read including GRAM read  and vert sync, dont ask me how to use them yet thought :-) ,the trick is to think of RD as read clock and WD as write clock , I tried buzzer on pwm, does not like it due to being piezo element and not a speaker  so it takes a moment to "charge up" before it produces sound. platformio.ini has the define for switching vectors bus it seems its not fully used as only changes part of the build, currently using BMP and thats got ISR at 0x800000 and stlink at 0x8007000, would be nice as i use both to just have the switch in platfomio.ini as -DVECT_TAB_OFFSET=0x0 or -DVECT_TAB_OFFSET=0x7000 to switch between no bootloader/bootloader (much faster dev wise to run without bootloader as the BMP writes direct to flash)

**Comment by delwinbest** [comment]
@darkspr1te Have a look at my latest mere into master. If added the ability to switch between two platformio environments. One with the MKS bootloader, and the other without. The problem seems to have been in the variant.cpp and linker scripts. Also, since moving to 'no bootloader' the LCD does not work in my version, which tells me we were relying on some of the init routines in the MKS bootloader. I'm going to look at porting the LCD libraries over and improve general handling on my repo.

**Comment by darkspr1te** [comment]
see _hw_special_init in HW_STM32F.h , that sets up PORTE and the config pins correctly , not included in my original commit, i've also ported the latest UTFT, URTOUCH, UTFT_Button,UTFT_graphics, SPIFlash from original UTFT website. Everything is now working (i see you also added the rmtree for the variant folder :-) ) , I will do a new commit soon with all the new libs and major tidy up and much better demos. basically everything is now working from a basic library in lib folder.

**Comment by darkspr1te** [comment]
So i've been cleaning up code and speeding up a lot of routines and building a base line code base from your vscode version , all libs are now at latest with cleaned up source, 
what do you think  https://www.youtube.com/watch?v=LzjbU5s8YZI

**Comment by delwinbest** [comment]
Hows flappy bird going? D
My master is up to date with what I've been messing with. Mainly cleaning up and moving around. Once i finish the touch part and LCD handling (through interrupt and outside of main.cpp) I''ll probably start looking at creating a 3d printer control interface.

**Comment by darkspr1te** [comment]
The flappy birds works great, have added game sound (cover the peizo to save your ears) and high score saving. it was to test read GRAM and the faster routines in UTFT that iv'e patched. much , much faster than my original upload, will have to add a proper vsync routine as code updates quicker than screen now. on the control interface side, take a look at https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware , they have some good products out (BigTreeTech) and the firmware is very similar to MKS offering, they are using F103/F105 chips though , prob cause the external SRAM options which will mate direct to LCD so you can treat it as ram.  The only part left now is USB host, i've avoided this part as i'am bad at it, dont understand the code quite yet, I also see why MKS left USB update out of the code and stuck with sdcard, code base is huge and exceeds 0x7000 limit for current bootloader, I have written a new bootloader with integral UTFT control and sdcard/serial firmware update, it also has a diagnostics option to test all inputs/outputs/devices. I will upload these soon as i've gone through and removed and logins/passwords :-) . Oh yeah that reminds , I have wifi working too with any esp2688 etc based devices and firmware update for that too.
