### ISSUE TITLE
Re implement LCD Init and libraries

### ISSUE THREAD

**Issue by delwinbest** [delwinbest/MKS-TFT28#4]
The LCD only works when using MKS bootloader, this implies there is missing init code in main software. Need to refactor and create feature parity between the two.

Relates to https://github.com/delwinbest/MKS-TFT28/issues/1

**Comment by darkspr1te** [comment]
Have added the missing code as one commit then added updated UTFT/URTouch as separate pull req so you can see whats missing from old code base.

**Comment by delwinbest** [comment]
@darkspr1te tested and works ! Thank you! 
I've refactored quite a bit, moved the LCD components into their own location (makes main.cpp eas to maintain. Also some refactoring of the routines you originally wrote. 

I've also edited platformio.io to allow for better collaboration
